server:
  port: ${SERVER_PORT:8081}
elasticsearch:
  url: ${ELASTICSEARCH_URL:https://localhost:9200}
  username: ${ELASTICSEARCH_USERNAME:elastic}
  password: ${ELASTICSEARCH_PASSWORD:HJ2qDhTJjvaohSvlyydN}